spring:
  application:
    name: event-notificator
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
  error:
    include-message: always

springdoc:
  swagger-ui:
    url: /event-notificator-openapi.yaml

jwt:
  secret-key: FEB29EE4F3B7CB24E421C81E119CFE2DD38FEC0CE212E4688A309C4C15A60145
  lifetime: 86400000